name: Find libspyrus

on:
  workflow_dispatch:

jobs:
  find_lib:
    runs-on: ubuntu-latest
    steps:
      - name: List and Find Spyrus
        run: |
          rsync -r --list-only rsync://46.43.14.141/platinum-stable/CMG-NAM64/ > rsync_tree.txt
          echo "=== SEARCHING FOR LIBSPYRUS ==="
          grep -i "spyrus" rsync_tree.txt
