name: Fetch SPYRUS Directory Tree

on:
  workflow_dispatch:

jobs:
  recon:
    runs-on: ubuntu-latest
    steps:
      - name: Recursively List Rsync Directory
        run: |
          echo "Scanning platinum-stable/CMG-NAM64 tree..."
          # -r ile recursive (alt klasörlerle) listeleme yapıyoruz
          rsync -r --list-only rsync://46.43.14.141/platinum-stable/CMG-NAM64/ > rsync_tree.txt
      
      - name: Upload Directory Tree
        uses: actions/upload-artifact@v4
        with:
          name: guralp-rsync-tree
          path: rsync_tree.txt
